// Code generated by genmap; DO NOT EDIT.
package lifi_dex_api

// Generated mapping helpers for struct -> map[string]any using tag: json
func (s *Token) ToMap() map[string]any {
	res := make(map[string]any, 9)
	if s.Address != "" { res["address"] = s.Address }
	if s.Symbol != "" { res["symbol"] = s.Symbol }
	if s.Name != "" { res["name"] = s.Name }
	if s.CoinKey != "" { res["coinKey"] = s.CoinKey }
	if s.LogoURI != "" { res["logoURI"] = s.LogoURI }
	if s.PriceUSD != "" { res["priceUSD"] = s.PriceUSD }
	return res
}

func (s *ErrorResponse) ToMap() map[string]any {
	res := make(map[string]any, 3)
	if s.Message != "" { res["message"] = s.Message }
	return res
}

func (s *AdvancedRoutesRequest) ToMap() map[string]any {
	res := make(map[string]any, 9)
	if s.FromAmount != "" { res["fromAmount"] = s.FromAmount }
	if s.FromTokenAddress != "" { res["fromTokenAddress"] = s.FromTokenAddress }
	if s.ToTokenAddress != "" { res["toTokenAddress"] = s.ToTokenAddress }
	if s.FromAddress != "" { res["fromAddress"] = s.FromAddress }
	if s.ToAddress != "" { res["toAddress"] = s.ToAddress }
	if s.FromAmountForGas != "" { res["fromAmountForGas"] = s.FromAmountForGas }
	return res
}

func (s *Bid) ToMap() map[string]any {
	res := make(map[string]any, 18)
	if s.User != "" { res["user"] = s.User }
	if s.Router != "" { res["router"] = s.Router }
	if s.Initiator != "" { res["initiator"] = s.Initiator }
	if s.SendingAssetId != "" { res["sendingAssetId"] = s.SendingAssetId }
	if s.Amount != "" { res["amount"] = s.Amount }
	if s.ReceivingAssetId != "" { res["receivingAssetId"] = s.ReceivingAssetId }
	if s.AmountReceived != "" { res["amountReceived"] = s.AmountReceived }
	if s.ReceivingAddress != "" { res["receivingAddress"] = s.ReceivingAddress }
	if s.TransactionId != "" { res["transactionId"] = s.TransactionId }
	if s.CallDataHash != "" { res["callDataHash"] = s.CallDataHash }
	if s.CallTo != "" { res["callTo"] = s.CallTo }
	if s.EncryptedCallData != "" { res["encryptedCallData"] = s.EncryptedCallData }
	if s.SendingChainTxManagerAddress != "" { res["sendingChainTxManagerAddress"] = s.SendingChainTxManagerAddress }
	if s.ReceivingChainTxManagerAddress != "" { res["receivingChainTxManagerAddress"] = s.ReceivingChainTxManagerAddress }
	return res
}

func (s *RouteStep) ToMap() map[string]any {
	res := make(map[string]any, 6)
	if s.Id != "" { res["id"] = s.Id }
	if s.Type != "" { res["type"] = s.Type }
	if s.Tool != "" { res["tool"] = s.Tool }
	if s.Integrator != "" { res["integrator"] = s.Integrator }
	return res
}

func (s *Route) ToMap() map[string]any {
	res := make(map[string]any, 12)
	if s.Id != "" { res["id"] = s.Id }
	if s.FromAmountUSD != "" { res["fromAmountUSD"] = s.FromAmountUSD }
	if s.FromAmount != "" { res["fromAmount"] = s.FromAmount }
	if s.ToAmountUSD != "" { res["toAmountUSD"] = s.ToAmountUSD }
	if s.ToAmount != "" { res["toAmount"] = s.ToAmount }
	if s.ToAmountMin != "" { res["toAmountMin"] = s.ToAmountMin }
	if s.GasCostUSD != "" { res["gasCostUSD"] = s.GasCostUSD }
	return res
}

func (s *RouteError) ToMap() map[string]any {
	res := make(map[string]any, 3)
	if s.ErrorType != "" { res["errorType"] = s.ErrorType }
	if s.Code != "" { res["code"] = s.Code }
	return res
}

func (s *APIError) ToMap() map[string]any {
	res := make(map[string]any, 5)
	if s.Method != "" { res["Method"] = s.Method }
	if s.URL != "" { res["URL"] = s.URL }
	return res
}

func (s *QuoteRequest) ToMap() map[string]any {
	res := make(map[string]any, 24)
	if s.FromChain != "" { res["fromChain"] = s.FromChain }
	if s.ToChain != "" { res["toChain"] = s.ToChain }
	if s.FromToken != "" { res["fromToken"] = s.FromToken }
	if s.ToToken != "" { res["toToken"] = s.ToToken }
	if s.FromAddress != "" { res["fromAddress"] = s.FromAddress }
	if s.ToAddress != "" { res["toAddress"] = s.ToAddress }
	if s.FromAmount != "" { res["fromAmount"] = s.FromAmount }
	if s.Order != "" { res["order"] = s.Order }
	if s.Integrator != "" { res["integrator"] = s.Integrator }
	if s.Referrer != "" { res["referrer"] = s.Referrer }
	if s.FromAmountForGas != "" { res["fromAmountForGas"] = s.FromAmountForGas }
	return res
}

func (s *QuoteResponse) ToMap() map[string]any {
	res := make(map[string]any, 10)
	if s.Id != "" { res["id"] = s.Id }
	if s.Type != "" { res["type"] = s.Type }
	if s.Tool != "" { res["tool"] = s.Tool }
	if s.Integrator != "" { res["integrator"] = s.Integrator }
	if s.Referrer != "" { res["referrer"] = s.Referrer }
	return res
}

func (s *StepEstimate) ToMap() map[string]any {
	res := make(map[string]any, 7)
	if s.FromAmount != "" { res["fromAmount"] = s.FromAmount }
	if s.ToAmount != "" { res["toAmount"] = s.ToAmount }
	if s.ToAmountMin != "" { res["toAmountMin"] = s.ToAmountMin }
	if s.ApprovalAddress != "" { res["approvalAddress"] = s.ApprovalAddress }
	return res
}

func (s *AdvancedRoutesResponse) ToMap() map[string]any {
	res := make(map[string]any, 3)
	return res
}

func (s *Config) ToMap() map[string]any {
	res := make(map[string]any, 4)
	if s.APIKey != "" { res["APIKey"] = s.APIKey }
	if s.BaseURL != "" { res["BaseURL"] = s.BaseURL }
	if s.ProxyURL != "" { res["ProxyURL"] = s.ProxyURL }
	return res
}

func (s *ToolDetails) ToMap() map[string]any {
	res := make(map[string]any, 3)
	if s.Key != "" { res["key"] = s.Key }
	if s.Name != "" { res["name"] = s.Name }
	if s.LogoURI != "" { res["logoURI"] = s.LogoURI }
	return res
}

func (s *FilteredOutError) ToMap() map[string]any {
	res := make(map[string]any, 2)
	if s.OverallPath != "" { res["overallPath"] = s.OverallPath }
	if s.Reason != "" { res["reason"] = s.Reason }
	return res
}

func (s *FailedError) ToMap() map[string]any {
	res := make(map[string]any, 2)
	if s.OverallPath != "" { res["overallPath"] = s.OverallPath }
	return res
}

func (s *Estimate) ToMap() map[string]any {
	res := make(map[string]any, 11)
	if s.Tool != "" { res["tool"] = s.Tool }
	if s.FromAmount != "" { res["fromAmount"] = s.FromAmount }
	if s.ToAmount != "" { res["toAmount"] = s.ToAmount }
	if s.ToAmountMin != "" { res["toAmountMin"] = s.ToAmountMin }
	if s.ApprovalAddress != "" { res["approvalAddress"] = s.ApprovalAddress }
	if s.FromAmountUSD != "" { res["fromAmountUSD"] = s.FromAmountUSD }
	if s.ToAmountUSD != "" { res["toAmountUSD"] = s.ToAmountUSD }
	return res
}

func (s *QuoteIncludedStep) ToMap() map[string]any {
	res := make(map[string]any, 6)
	if s.Id != "" { res["id"] = s.Id }
	if s.Type != "" { res["type"] = s.Type }
	if s.Tool != "" { res["tool"] = s.Tool }
	return res
}

func (s *Client) ToMap() map[string]any {
	res := make(map[string]any, 0)
	return res
}

func (s *Action) ToMap() map[string]any {
	res := make(map[string]any, 8)
	if s.FromAmount != "" { res["fromAmount"] = s.FromAmount }
	if s.FromAddress != "" { res["fromAddress"] = s.FromAddress }
	if s.ToAddress != "" { res["toAddress"] = s.ToAddress }
	return res
}

func (s *Transaction) ToMap() map[string]any {
	res := make(map[string]any, 14)
	if s.TxHash != "" { res["txHash"] = s.TxHash }
	if s.TxLink != "" { res["txLink"] = s.TxLink }
	if s.Amount != "" { res["amount"] = s.Amount }
	if s.GasPrice != "" { res["gasPrice"] = s.GasPrice }
	if s.GasUsed != "" { res["gasUsed"] = s.GasUsed }
	if s.GasAmount != "" { res["gasAmount"] = s.GasAmount }
	if s.GasAmountUSD != "" { res["gasAmountUSD"] = s.GasAmountUSD }
	if s.AmountUSD != "" { res["amountUSD"] = s.AmountUSD }
	if s.Value != "" { res["value"] = s.Value }
	return res
}

func (s *IncludedStep) ToMap() map[string]any {
	res := make(map[string]any, 7)
	if s.Tool != "" { res["tool"] = s.Tool }
	if s.FromAmount != "" { res["fromAmount"] = s.FromAmount }
	if s.ToAmount != "" { res["toAmount"] = s.ToAmount }
	if s.BridgedAmount != "" { res["bridgedAmount"] = s.BridgedAmount }
	return res
}

func (s *RouteOptions) ToMap() map[string]any {
	res := make(map[string]any, 9)
	if s.Integrator != "" { res["integrator"] = s.Integrator }
	if s.Referrer != "" { res["referrer"] = s.Referrer }
	if s.Order != "" { res["order"] = s.Order }
	return res
}

func (s *StepEstimateData) ToMap() map[string]any {
	res := make(map[string]any, 11)
	if s.GasFeeInReceivingToken != "" { res["gasFeeInReceivingToken"] = s.GasFeeInReceivingToken }
	if s.TotalFee != "" { res["totalFee"] = s.TotalFee }
	if s.MetaTxRelayerFee != "" { res["metaTxRelayerFee"] = s.MetaTxRelayerFee }
	if s.RouterFee != "" { res["routerFee"] = s.RouterFee }
	if s.ToTokenAmount != "" { res["toTokenAmount"] = s.ToTokenAmount }
	if s.FromTokenAmount != "" { res["fromTokenAmount"] = s.FromTokenAmount }
	return res
}

func (s *Subpath) ToMap() map[string]any {
	res := make(map[string]any, 5)
	if s.ErrorType != "" { res["errorType"] = s.ErrorType }
	if s.Code != "" { res["code"] = s.Code }
	if s.Tool != "" { res["tool"] = s.Tool }
	if s.Message != "" { res["message"] = s.Message }
	return res
}

func (s *Protocol) ToMap() map[string]any {
	res := make(map[string]any, 4)
	if s.Name != "" { res["name"] = s.Name }
	if s.FromTokenAddress != "" { res["fromTokenAddress"] = s.FromTokenAddress }
	if s.ToTokenAddress != "" { res["toTokenAddress"] = s.ToTokenAddress }
	return res
}

func (s *APIErrorPayload) ToMap() map[string]any {
	res := make(map[string]any, 4)
	if s.Type != "" { res["type"] = s.Type }
	if s.Subtype != "" { res["subtype"] = s.Subtype }
	if s.Amount != "" { res["amount"] = s.Amount }
	if s.Message != "" { res["message"] = s.Message }
	return res
}

func (s *GasCost) ToMap() map[string]any {
	res := make(map[string]any, 7)
	if s.Type != "" { res["type"] = s.Type }
	if s.Price != "" { res["price"] = s.Price }
	if s.Amount != "" { res["amount"] = s.Amount }
	if s.Estimate != "" { res["estimate"] = s.Estimate }
	if s.Limit != "" { res["limit"] = s.Limit }
	if s.AmountUSD != "" { res["amountUSD"] = s.AmountUSD }
	return res
}

func (s *Errors) ToMap() map[string]any {
	res := make(map[string]any, 2)
	return res
}

func (s *StatusResponse) ToMap() map[string]any {
	res := make(map[string]any, 13)
	if s.TransactionId != "" { res["transactionId"] = s.TransactionId }
	if s.LifiExplorerLink != "" { res["lifiExplorerLink"] = s.LifiExplorerLink }
	if s.FromAddress != "" { res["fromAddress"] = s.FromAddress }
	if s.ToAddress != "" { res["toAddress"] = s.ToAddress }
	if s.Tool != "" { res["tool"] = s.Tool }
	if s.Status != "" { res["status"] = s.Status }
	if s.Substatus != "" { res["substatus"] = s.Substatus }
	if s.SubstatusMessage != "" { res["substatusMessage"] = s.SubstatusMessage }
	if s.BridgeExplorerLink != "" { res["bridgeExplorerLink"] = s.BridgeExplorerLink }
	return res
}

func (s *FeeCost) ToMap() map[string]any {
	res := make(map[string]any, 7)
	if s.Name != "" { res["name"] = s.Name }
	if s.Description != "" { res["description"] = s.Description }
	if s.Percentage != "" { res["percentage"] = s.Percentage }
	if s.Amount != "" { res["amount"] = s.Amount }
	if s.AmountUSD != "" { res["amountUSD"] = s.AmountUSD }
	return res
}

func (s *StatusRequest) ToMap() map[string]any {
	res := make(map[string]any, 4)
	if s.TxHash != "" { res["txHash"] = s.TxHash }
	if s.Bridge != "" { res["bridge"] = s.Bridge }
	if s.FromChain != "" { res["fromChain"] = s.FromChain }
	if s.ToChain != "" { res["toChain"] = s.ToChain }
	return res
}

func (s *SendingTransaction) ToMap() map[string]any {
	res := make(map[string]any, 14)
	if s.TxHash != "" { res["txHash"] = s.TxHash }
	if s.TxLink != "" { res["txLink"] = s.TxLink }
	if s.Amount != "" { res["amount"] = s.Amount }
	if s.GasPrice != "" { res["gasPrice"] = s.GasPrice }
	if s.GasUsed != "" { res["gasUsed"] = s.GasUsed }
	if s.GasAmount != "" { res["gasAmount"] = s.GasAmount }
	if s.GasAmountUSD != "" { res["gasAmountUSD"] = s.GasAmountUSD }
	if s.AmountUSD != "" { res["amountUSD"] = s.AmountUSD }
	if s.Value != "" { res["value"] = s.Value }
	return res
}

func (s *TransactionRequest) ToMap() map[string]any {
	res := make(map[string]any, 7)
	if s.From != "" { res["from"] = s.From }
	if s.To != "" { res["to"] = s.To }
	if s.Data != "" { res["data"] = s.Data }
	if s.Value != "" { res["value"] = s.Value }
	if s.GasPrice != "" { res["gasPrice"] = s.GasPrice }
	if s.GasLimit != "" { res["gasLimit"] = s.GasLimit }
	return res
}

